import os

ROOT_PATH = os.path.dirname(__file__)

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

PLAYER = "Player"
BOT = "Bot"

PADDING_BORDER_DISTANCE_X = 30
PADDING_BORDER_DISTANCE_Y = 90

MAX_FRAME_RATE = 60

WINNING_SCORE = 2

REFLECT_SPEED_MULTIPLIER = 1.05

BALL_SIZE = 12
BALL_INITIAL_SPEED = 500

PADDLE_WIDTH = 15
PADDLE_HEIGHT = 60
PADDLE_EXTEND = 30
PADDLE_SPEED = 600

ENERGY_MAX = 50
ENERGY_WIDTH = 24
ENERGY_HEIGHT = 50
ENERGY_SPACE = 8

COLOR_BACKGROUND = (40, 45, 52)
COLOR_WHITE = (255, 255, 255)
COLOR_RED = (255, 0, 0)
COLOR_GREEN = (0, 255, 0)
COLOR_BLUE = (0, 0, 255)
COLOR_LIGHT_BLUE = (206, 229, 237)
COLOR_ORANGE = (255, 165, 0)

STATE_START = "STATE_START"
STATE_SERVE = "STATE_SERVE"
STATE_PLAY = "STATE_PLAY"
STATE_DONE = "STATE_DONE"

SOUND_PADDLE_HIT = "SOUND_PADDLE_HIT"
SOUND_WALL_HIT = "SOUND_WALL_HIT"
SOUND_SCORE = "SOUND_SCORE"

BOT_EASY = "BOT_EASY"
BOT_HARD = "BOT_HARD"
BOT_HARD_HEIGHT = 120
